In [1]:
#helloworld

### Master in Data Science - Data Science Toolkit Notes

#### Addition

In [4]:
5 + 5 *2 #testing addition

15

In [5]:
print(100 * 1.1 ** 7) #I have 100$ with a 10% return each year

194.87171000000012


In [6]:
message = "Hi there" #variable

In [7]:
print(message)

Hi there


In [8]:
savings = 100
growth = 1.1
result = savings * growth ** 7
print(result)

194.87171000000012


In [9]:
#integer: 1
#float: 1.2
# string: string of letters, abc
# bool: boolean, true or false

In [11]:
type(growth) #checking the type of a code

float

##### Variables (This is a markdown cell)

In [12]:
savings_string = "100"
print(savings_string)

100


In [13]:
type(savings_string)

str

#### Lists

In [15]:
numberlistname = [1,2,3,4,5]

In [18]:
shoppinglist = ["banana", "apple", "pineapple"]
print(shoppinglist)

['banana', 'apple', 'pineapple']


In [20]:
hall = 11.1
kit = 12.1
bed = 13.2

#create list
areas = [hall, kit,bed, "bedroom", "kitchen"]

#print
print(areas)

[11.1, 12.1, 13.2, 'bedroom', 'kitchen']


#### List indexing

In [21]:
#indexing starts at 0

In [24]:
areas[3] #getting the 4th element from the list

'bedroom'

In [28]:
#negative indexing
areas[-2]

'bedroom'

In [30]:
print(areas)
print(areas[3])

[11.1, 12.1, 13.2, 'bedroom', 'kitchen']
bedroom


In [32]:
areas[1:3]

[12.1, 13.2]

In [35]:
areas[0] = "focus" #updating list
print(areas)

['focus', 12.1, 13.2, 'bedroom', 'kitchen']


In [36]:
areas[2:] = ["focus", "focuson"]

In [37]:
print(areas)

['focus', 12.1, 'focus', 'focuson']


#### Appending Lists

In [38]:
# list + list

areas2 = [1,2,3,4,5]
total = areas + areas2
print(total)


['focus', 12.1, 'focus', 'focuson', 1, 2, 3, 4, 5]


#### Delete Elements

In [39]:
del(total[1])
print(total)

['focus', 'focus', 'focuson', 1, 2, 3, 4, 5]


#### Copying Lists

In [40]:
# copying content from a list to another
y = total[ : ]
print(y)

['focus', 'focus', 'focuson', 1, 2, 3, 4, 5]


In [41]:
del(y[1])
print(y)

['focus', 'focuson', 1, 2, 3, 4, 5]


#### Functions

In [48]:
#block of code — when you call a function, it runs and returns output
#output = function(input)

var1 = [1,2,3,4,5]
var2 = True

#print type
print(type(var1))

#print length of a list!
print(len(var1))

#convert var2 to an integer: number
number = int(var2)
print(number)



<class 'list'>
5
1


#### How to get help for a function

In [49]:
?print #how to get more info of a function

In [51]:
help(print) # same as above

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [52]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [55]:
# sorted function can help sort items in a list

list = [1,2,5,7,9,10]
sorted(list, reverse=True) #sorting reverse order

[10, 9, 7, 5, 2, 1]

#### Methods

In [62]:
focus = "Iamindeedfocused"
print(focus.replace('a', 'A'))

IAmindeedfocused


#### index() to find the index
#### count() to find how many times something appears
#### append() to add to the list
#### reverse() to reverse the list 

#### Packages

In [68]:
# install package add pip
# if you have it add import

In [65]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [67]:
import numpy as np

In [70]:
#create an array
np.array(['a', 'b', 'c', 'd'])

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [73]:
#create an array of ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x[:5] #first 5 

array([0, 1, 2, 3, 4])

In [78]:
x[4:] #after index 4

array([4, 5, 6, 7, 8, 9])

In [82]:
high = x > 5
print(high) #boolean list

x[high]

[False False False False False False  True  True  True  True]


array([6, 7, 8, 9])

In [87]:
list = [[1,2], [2,3],[3,4]]

array = np.array(list) #create a 2D np array

print(array.shape) #check the size, 3 rows, 2 columns

(3, 2)


#### Numpy Statistics

#np.mean()
#np.median()
#np.std()
#np.corrcoeff()